### ISSUE TITLE
Failed to train

### ISSUE THREAD

**Issue by attardi** [emorynlp/iwpt-shared-task-2020#1]
Thank you for sharing the code.

I tried to train the parser on the data from IWPT 2020 ST.

In  all_in_one.py I changed 

    all_in_one.pyif sys.argv[1] == 'train':
             run(langcode, do_train=True, mbert=False, do_eval=False)
         else:
             run(langcode, do_train=False, mbert=True, do_eval=True)

In iwpt2020/shorten.py I commented out the lines:

         if langcode != 'en':
             continue

in order for it to produce the shortened data used for training
I uncommented these lines from iwpt2020/combine_treebanks.py:

        for part in ['train', 'dev']:
            combine(fs, f'{part}.enhanced_collapse_empty_nodes.conllu', f'{folder}/{part}.co
 
However I get this error:

2020-06-20 00:56:10.332775: W tensorflow/core/common_runtime/executor.cc:2046] 0x7f6118022e30 Compute status: Out of range: StopIteration: 
Traceback (most recent call last):

  File "/homenfs/tempGPU/iwpt2020/.env/lib64/python3.6/site-packages/tensorflow_core/python/ops/script_ops.py", line 236, in __call__
    ret = func(*args)

  File "/homenfs/tempGPU/iwpt2020/.env/lib64/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 789, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

StopIteration

	 [[{{node PyFunc}}]]
2020-06-20 00:56:10.332855: W tensorflow/core/common_runtime/executor.cc:2462] Dumping state
2020-06-20 00:56:10.332874: W tensorflow/core/common_runtime/executor.cc:2464] 
2020-06-20 00:56:10.332889: W tensorflow/core/common_runtime/executor.cc:1217]   Iteration:
2020-06-20 00:56:10.332919: W tensorflow/core/common_runtime/executor.cc:2389]     Pending Node: {name:'identity_RetVal' id:4 def:{{{node identity_RetVal}} = _Retval[T=DT_INT64, index=0](PyFunc)}}
2020-06-20 00:56:10.332941: W tensorflow/core/common_runtime/executor.cc:2394]       Input 0: Tensor<type: float shape: [0]>
2020-06-20 00:56:10.332963: W tensorflow/core/common_runtime/executor.cc:2389]     Pending Node: {name:'identity_1_RetVal' id:5 def:{{{node identity_1_RetVal}} = _Retval[T=DT_INT64, index=1](PyFunc:1)}}
2020-06-20 00:56:10.332980: W tensorflow/core/common_runtime/executor.cc:2394]       Input 0: Tensor<type: float shape: [0]>
2020-06-20 00:56:10.332999: W tensorflow/core/common_runtime/executor.cc:2389]     Pending Node: {name:'identity_2_RetVal' id:6 def:{{{node identity_2_RetVal}} = _Retval[T=DT_INT64, index=2](PyFunc:2)}}
2020-06-20 00:56:10.333016: W tensorflow/core/common_runtime/executor.cc:2394]       Input 0: Tensor<type: float shape: [0]>
2020-06-20 00:56:10.333035: W tensorflow/core/common_runtime/executor.cc:2389]     Pending Node: {name:'identity_3_RetVal' id:7 def:{{{node identity_3_RetVal}} = _Retval[T=DT_INT64, index=3](PyFunc:3)}}
2020-06-20 00:56:10.333052: W tensorflow/core/common_runtime/executor.cc:2394]       Input 0: Tensor<type: float shape: [0]>
2020-06-20 00:56:10.333070: W tensorflow/core/common_runtime/executor.cc:2389]     Pending Node: {name:'identity_4_RetVal' id:8 def:{{{node identity_4_RetVal}} = _Retval[T=DT_INT64, index=4](PyFunc:4)}}
2020-06-20 00:56:10.333087: W tensorflow/core/common_runtime/executor.cc:2394]       Input 0: Tensor<type: float shape: [0]>
2020-06-20 00:56:10.333106: W tensorflow/core/common_runtime/executor.cc:2389]     Pending Node: {name:'identity_5_RetVal' id:9 def:{{{node identity_5_RetVal}} = _Retval[T=DT_INT64, index=5](PyFunc:5)}}
2020-06-20 00:56:10.333123: W tensorflow/core/common_runtime/executor.cc:2394]       Input 0: Tensor<type: float shape: [0]>
2020-06-20 00:56:10.333156: W tensorflow/core/common_runtime/executor.cc:2407]     Active Node: {name:'PyFunc' id:3 def:{{{node PyFunc}} = PyFunc[Tin=[DT_INT64], Tout=[DT_INT64, DT_INT64, DT_INT64, DT_INT64, DT_INT64, DT_INT64], token="pyfunc_1"](args_0)}}
2020-06-20 00:56:10.333176: W tensorflow/core/common_runtime/executor.cc:2413]       Input 0: Tensor<type: int64 shape: []>
2020-06-20 00:56:10.333195: W tensorflow/core/common_runtime/executor.cc:2448]     Input 0: Tensor<type: int64 shape: [], bytes: 8>
2020-06-20 00:56:10.333211: W tensorflow/core/common_runtime/executor.cc:2448]     Input 1: Tensor<type: float shape: [0], bytes: 0>
2020-06-20 00:56:10.333227: W tensorflow/core/common_runtime/executor.cc:2448]     Input 2: Tensor<type: float shape: [0], bytes: 0>
2020-06-20 00:56:10.333249: W tensorflow/core/common_runtime/executor.cc:2448]     Input 3: Tensor<type: float shape: [0], bytes: 0>
2020-06-20 00:56:10.333265: W tensorflow/core/common_runtime/executor.cc:2448]     Input 4: Tensor<type: float shape: [0], bytes: 0>
2020-06-20 00:56:10.333280: W tensorflow/core/common_runtime/executor.cc:2448]     Input 5: Tensor<type: float shape: [0], bytes: 0>
2020-06-20 00:56:10.333295: W tensorflow/core/common_runtime/executor.cc:2448]     Input 6: Tensor<type: float shape: [0], bytes: 0>
2020-06-20 00:56:10.333310: W tensorflow/core/common_runtime/executor.cc:2456]     Total bytes 8
2020-06-20 00:56:10.333611: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
2020-06-20 00:56:10.593986: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at transpose_op.cc:157 : Invalid argument: transpose expects a vector of size 3. But input(1) is a vector of size 4
01/17 ar.txt
Traceback (most recent call last):
  File "all_in_one.py", line 319, in <module>
    main()
  File "all_in_one.py", line 313, in main
    run(langcode, do_train=True, mbert=False, do_eval=False)
  File "all_in_one.py", line 103, in run
    learning_rate_transformer=1e-5,
  File "/homenfs/tempGPU/iwpt2020/iwpt-shared-task-2020/edparser/components/parsers/biaffine_parser.py", line 459, in fit
    return KerasComponent.fit(self, **merge_locals_kwargs(locals(), kwargs))
  File "/homenfs/tempGPU/iwpt2020/iwpt-shared-task-2020/edparser/common/keras_component.py", line 297, in fit
    model, optimizer, loss, metrics = self.build(**merge_dict(self.config, logger=logger, training=True))
  File "/homenfs/tempGPU/iwpt2020/iwpt-shared-task-2020/edparser/common/keras_component.py", line 210, in build
    self.model(sample_inputs, training=kwargs.get('training', None))
  File "/homenfs/tempGPU/iwpt2020/.env/lib64/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 822, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/homenfs/tempGPU/iwpt2020/iwpt-shared-task-2020/edparser/components/parsers/biaffine/model.py", line 122, in call
    s_rel = tf.transpose(self.rel_attn(rel_d, rel_h), [0, 2, 3, 1])
  File "/homenfs/tempGPU/iwpt2020/.env/lib64/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 1866, in transpose_v2
    return transpose(a=a, perm=perm, name=name, conjugate=conjugate)
  File "/homenfs/tempGPU/iwpt2020/.env/lib64/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 1946, in transpose
    return transpose_fn(a, perm, name=name)
  File "/homenfs/tempGPU/iwpt2020/.env/lib64/python3.6/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 10530, in transpose
    x, perm, name=name, ctx=_ctx)
  File "/homenfs/tempGPU/iwpt2020/.env/lib64/python3.6/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 10557, in transpose_eager_fallback
    attrs=_attrs, ctx=ctx, name=name)
  File "/homenfs/tempGPU/iwpt2020/.env/lib64/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: transpose expects a vector of size 3. But input(1) is a vector of size 4 [Op:Transpose] name: biaffine_model/transpose/

**Comment by hankcs** [comment]
Hi, I found the preprocessing code was messed up and submitted several fixes just now. Could you checkout [this link](https://github.com/emorynlp/iwpt-shared-task-2020/tree/master/data/iwpt2020)?

**Comment by attardi** [comment]
It works now.
Thank you.
